version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/nchapman/lleme/internal/version.Version={{.Version}}
    binary: lleme

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: lleme
    repository:
      owner: nchapman
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/nchapman/lleme"
    description: "Run local LLMs with llama.cpp and Hugging Face"
    license: "MIT"
    install: |
      bin.install "lleme"
    service: |
      run [opt_bin/"lleme", "server", "start"]
      keep_alive crashed: true
      log_path var/"log/lleme.log"
      error_log_path var/"log/lleme.log"
